apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  tasks:
    - name: hello
      taskSpec:
        steps:
          - name: echo
            image: alpine
            script: |
              #!/bin/sh
              echo "Hello Tekton!"
    - name: goodbye
      runAfter:
        - hello
      taskSpec:
        steps:
          - name: goodbye
            image: alpine
            script: |
              #!/bin/sh
              echo "Goodbye World!"
